# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heitor's log
description: Yeaah
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heitorpb.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
encoding: utf-8

# make blog at /bla/*
permalink: /bla/:year/:month/:day/:title/

name: Heitor de Bittencourt
author: Heitor de Bittencourt
#tagline: Physicist
#email: your-email@example.com
#twitter_username:
#github_username: heitorPB
logo: "/assets/imgs/qrcode.png"

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-postfiles
  - jekyll/twemoji

include:
   - random/

defaults:
  - scope:
      path: "/random/*.md"
    values:
      sitemap: false
  - scope:
      path: "google*.html"
    values:
      sitemap: false
  - scope:
      path: "/_posts/**.md"
    values:
      image: "/assets/imgs/me.jpg"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - README.md
   - Gemfile
   - Gemfile.lock
   - run-jekyll.sh
   - _posts/template.md
